name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: docker build -t andrykar/todolist-server:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
    - name: login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: push
      run: docker push andrykar/todolist-server:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: render config
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
          cat .env | envsubst > deploy/.env
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "deploy/docker-compose.yaml"
          target: "todolist-server"
          strip_components: 1