version: '3.10'

services:
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/code
  front:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - postgres
      - api
  migration:
    image: api
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - postgres

volumes:
  postgres_data:
  front: