name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: docker build -t andrykar/todolist-server:$GITHUB_REF_NAME-$GITHUB_RUN_ID ./todolist
    - name: login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: push
      run: docker push andrykar/todolist-server:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: render config
        run: |
          mkdir deploy
          cat todolist/docker-compose-ci.yaml | envsubst > deploy/docker-compose-ci.yaml
          echo ${{ secrets.DEBUG }} >> .env
          echo ${{ secrets.SECRET_KEY }} >> .env
          echo ${{ secrets.DJANGO_ALLOWED_HOSTS }} >> .env
          echo ${{ secrets.SQL_ENGINE }} >> .env
          echo ${{ secrets.SQL_DATABASE }} >> .env
          echo ${{ secrets.SQL_USER }} >> .env
          echo ${{ secrets.SQL_PASSWORD }} >> .env
          echo ${{ secrets.SQL_HOST }} >> .env
          echo ${{ secrets.SQL_PORT }} >> .env
          cat .env | envsubst > deploy/.env
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_KEY }}
          source: "todolist/docker-compose-ci.yaml,todolist/.env"
          target: "todolist-server"
          strip_components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd todolist-server
            cat docker-compose-ci.yaml > docker-compose.yaml
            rm docker-compose-ci.yaml
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker-compose up -d